<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Rajesh-PC" ignored="0" name="Test1" tests="1" failures="1" timestamp="10 Jun 2025 11:56:10 GMT" time="45.764" errors="0">
  <testcase name="verify_Account_Registration" time="2.329" classname="testCases.TG001_AccountRegistrationTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at testCases.TG001_AccountRegistrationTest.verify_Account_Registration(TG001_AccountRegistrationTest.java:95)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- verify_Account_Registration -->
</testsuite> <!-- Test1 -->
